name: CI

on: [push, pull_request]

jobs:
  compile-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "12"
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: VSCE package
        run: npm run package

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "12"
      - name: Install dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint

  grammar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "12"
      - name: Install dependencies
        run: npm install
      - name: Run grammar tests
        run: npm run test testgrammar
